package com.spendwise.alerts;

import com.spendwise.auth.FirebaseAuthTestConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Covers the Required Tests for E5-S4 (docs/api.md `/alerts`). Requires Docker — run via
 * {@code ./gradlew integrationTest}. Alerts have no write endpoint of their own (they're
 * system-generated by {@link AlertEvaluatorJob}), so this seeds directly through {@link
 * AlertsService} — the same "autowire the collaborator directly" approach {@code
 * CategorizationJobsIntegrationTest} uses for its scheduled-job classes.
 */
@Testcontainers
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(FirebaseAuthTestConfig.class)
class AlertControllerIntegrationTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16");

    @Autowired
    private AlertsService alertsService;

    @Autowired
    private TestRestTemplate restTemplate;

    @LocalServerPort
    private int port;

    private String baseUrl() {
        return "http://localhost:" + port + "/api/v1";
    }

    @Test
    void markReadFlipsIsReadWithoutTouchingDeliveredAt() {
        Session session = loginPhone("+919100000090");
        Alert seeded = seedAlert(session.userId(), AlertType.CATEGORY_OVERSPEND, 5);

        ResponseEntity<Void> markRead = restTemplate.exchange(
                baseUrl() + "/alerts/" + seeded.id() + "/read", HttpMethod.PUT, new HttpEntity<>(session.headers()), Void.class);
        assertThat(markRead.getStatusCode()).isEqualTo(HttpStatus.OK);

        ResponseEntity<Map> list =
                restTemplate.exchange(baseUrl() + "/alerts", HttpMethod.GET, new HttpEntity<>(session.headers()), Map.class);
        Map<?, ?> alertRow = findAlert(list, seeded.id());
        assertThat(alertRow.get("isRead")).isEqualTo(true);
        assertThat(alertRow.get("deliveredAt")).isNull();
    }

    @Test
    void isReadFilterReturnsOnlyUnreadAlerts() {
        Session session = loginPhone("+919100000091");
        Alert unread = seedAlert(session.userId(), AlertType.CATEGORY_APPROACHING_LIMIT, 6);
        Alert readAlert = seedAlert(session.userId(), AlertType.MID_MONTH_BUDGET, null);
        restTemplate.exchange(
                baseUrl() + "/alerts/" + readAlert.id() + "/read", HttpMethod.PUT, new HttpEntity<>(session.headers()), Void.class);

        ResponseEntity<Map> unreadOnly = restTemplate.exchange(
                baseUrl() + "/alerts?is_read=false", HttpMethod.GET, new HttpEntity<>(session.headers()), Map.class);

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> data = (List<Map<String, Object>>) unreadOnly.getBody().get("data");
        assertThat(data).extracting(row -> row.get("id")).contains(unread.id().toString());
        assertThat(data).extracting(row -> row.get("id")).doesNotContain(readAlert.id().toString());
    }

    @Test
    void userBCannotMarkUserAsAlertAsRead() {
        Session userA = loginPhone("+919100000092");
        Alert seeded = seedAlert(userA.userId(), AlertType.CATEGORY_OVERSPEND, 7);
        Session userB = loginGoogle();

        ResponseEntity<Map> response = restTemplate.exchange(
                baseUrl() + "/alerts/" + seeded.id() + "/read", HttpMethod.PUT, new HttpEntity<>(userB.headers()), Map.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
    }

    private Alert seedAlert(UUID userId, AlertType type, Integer categoryId) {
        Map<String, Object> payload = categoryId == null ? Map.of() : Map.of("category_id", categoryId);
        return alertsService
                .recordIfNotAlreadyTriggeredThisMonth(userId, type, categoryId, AlertPriority.HIGH, payload)
                .orElseThrow();
    }

    private Map<?, ?> findAlert(ResponseEntity<Map> list, UUID alertId) {
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> data = (List<Map<String, Object>>) list.getBody().get("data");
        return data.stream().filter(row -> row.get("id").equals(alertId.toString())).findFirst().orElseThrow();
    }

    private Session loginPhone(String phone) {
        ResponseEntity<Map> verify = restTemplate.postForEntity(
                baseUrl() + "/auth/otp/verify",
                Map.of("phone", phone, "idToken", FirebaseAuthTestConfig.VALID_OTP_TOKEN_PHONE_A),
                Map.class);
        return toSession(verify);
    }

    private Session loginGoogle() {
        ResponseEntity<Map> verify = restTemplate.postForEntity(
                baseUrl() + "/auth/google", Map.of("idToken", FirebaseAuthTestConfig.VALID_GOOGLE_TOKEN_A), Map.class);
        return toSession(verify);
    }

    private Session toSession(ResponseEntity<Map> response) {
        String accessToken = (String) response.getBody().get("accessToken");
        String userId = (String) ((Map<?, ?>) response.getBody().get("user")).get("id");
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(accessToken);
        headers.setContentType(MediaType.APPLICATION_JSON);
        return new Session(UUID.fromString(userId), headers);
    }

    private record Session(UUID userId, HttpHeaders headers) {}
}
