package com.spendwise.alerts;

import com.spendwise.auth.FirebaseAuthTestConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Covers the Required Tests for E5-S4 (docs/api.md `/alerts`). Requires Docker — run via
 * {@code ./gradlew integrationTest}. Alerts have no write endpoint of their own (they're
 * system-generated by {@link AlertEvaluatorJob}), so this seeds directly through {@link
 * AlertsService} — the same "autowire the collaborator directly" approach {@code
 * CategorizationJobsIntegrationTest} uses for its scheduled-job classes.
 */
@Testcontainers
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(FirebaseAuthTestConfig.class)
class AlertControllerIntegrationTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16");

    @Autowired
    private AlertsService alertsService;

    @Autowired
    private TestRestTemplate restTemplate;

    @LocalServerPort
    private int port;

    private String baseUrl() {
        return "http://localhost:" + port + "/api/v1";
    }

    @Test
    void markReadFlipsIsReadWithoutTouchingDeliveredAt() {
        Session session = loginPhone("+919100000090");
        Alert seeded = seedAlert(session.userId(), AlertType.CATEGORY_OVERSPEND, 5);

        ResponseEntity<Void> markRead = restTemplate.exchange(
                baseUrl() + "/alerts/" + seeded.id() + "/read", HttpMethod.PUT, new HttpEntity<>(session.headers()), Void.class);
        assertThat(markRead.getStatusCode()).isEqualTo(HttpStatus.OK);

        ResponseEntity<Map> list =
                restTemplate.exchange(baseUrl() + "/alerts", HttpMethod.GET, new HttpEntity<>(session.headers()), Map.class);
        Map<?, ?> alertRow = findAlert(list, seeded.id());
        assertThat(alertRow.get("isRead")).isEqualTo(true);
        assertThat(alertRow.get("deliveredAt")).isNull();
    }

    @Test
    void isReadFilterReturnsOnlyUnreadAlerts() {
        Session session = loginPhone("+919100000091");
        Alert unread = seedAlert(session.userId(), AlertType.CATEGORY_APPROACHING_LIMIT, 6);
        Alert readAlert = seedAlert(session.userId(), AlertType.MID_MONTH_BUDGET, null);
        restTemplate.exchange(
                baseUrl() + "/alerts/" + readAlert.id() + "/read", HttpMethod.PUT, new HttpEntity<>(session.headers()), Void.class);

        ResponseEntity<Map> unreadOnly = restTemplate.exchange(
                baseUrl() + "/alerts?is_read=false", HttpMethod.GET, new HttpEntity<>(session.headers()), Map.class);

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> data = (List<Map<String, Object>>) unreadOnly.getBody().get("data");
        assertThat(data).extracting(row -> row.get("id")).contains(unread.id().toString());
        assertThat(data).extracting(row -> row.get("id")).doesNotContain(readAlert.id().toString());
    }

    @Test
    void userBCannotMarkUserAsAlertAsRead() {
        Session userA = loginPhone("+919100000092");
        Alert seeded = seedAlert(userA.userId(), AlertType.CATEGORY_OVERSPEND, 7);
        Session userB = loginGoogle();

        ResponseEntity<Map> response = restTemplate.exchange(
                baseUrl() + "/alerts/" + seeded.id() + "/read", HttpMethod.PUT, new HttpEntity<>(userB.headers()), Map.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
    }

    @Test
    void confirmCreatesTheLinkedEmiAndSecondConfirmIsANoOp() throws Exception {
        Session session = loginPhone("+919100000093");
        UUID sourceTransactionId = insertTransactionDirectly(session.userId(), "netflix@okicici", "Netflix", "199.00");
        Alert alert = seedRecurringPaymentAlert(session.userId(), "netflix@okicici", "Netflix", sourceTransactionId);

        ResponseEntity<Map> firstConfirm = restTemplate.exchange(
                baseUrl() + "/alerts/" + alert.id() + "/confirm", HttpMethod.POST, new HttpEntity<>(session.headers()), Map.class);
        assertThat(firstConfirm.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(firstConfirm.getBody().get("detectedFromSms")).isEqualTo(true);
        assertThat(firstConfirm.getBody().get("sourceTransactionId")).isEqualTo(sourceTransactionId.toString());
        assertThat(firstConfirm.getBody().get("isActive")).isEqualTo(true);
        String emiId = (String) firstConfirm.getBody().get("id");
        assertThat(countEmisForSourceTransaction(sourceTransactionId)).isEqualTo(1);

        ResponseEntity<Map> secondConfirm = restTemplate.exchange(
                baseUrl() + "/alerts/" + alert.id() + "/confirm", HttpMethod.POST, new HttpEntity<>(session.headers()), Map.class);
        assertThat(secondConfirm.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(secondConfirm.getBody().get("id")).isEqualTo(emiId);
        assertThat(countEmisForSourceTransaction(sourceTransactionId)).isEqualTo(1);
    }

    @Test
    void dismissMarksReadWithoutCreatingAnEmi() throws Exception {
        Session session = loginPhone("+919100000094");
        UUID sourceTransactionId = insertTransactionDirectly(session.userId(), "spotify@okhdfc", "Spotify", "119.00");
        Alert alert = seedRecurringPaymentAlert(session.userId(), "spotify@okhdfc", "Spotify", sourceTransactionId);

        ResponseEntity<Void> dismiss = restTemplate.exchange(
                baseUrl() + "/alerts/" + alert.id() + "/read", HttpMethod.PUT, new HttpEntity<>(session.headers()), Void.class);

        assertThat(dismiss.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(countEmisForSourceTransaction(sourceTransactionId)).isEqualTo(0);
    }

    @Test
    void confirmingANonRecurringPaymentAlertReturns400() {
        Session session = loginPhone("+919100000095");
        // Distinct category id from markReadFlipsIsReadWithoutTouchingDeliveredAt's CATEGORY_OVERSPEND
        // seed (id 5) — every loginPhone(...) call in this class resolves to the same fixed-token test
        // identity (see FirebaseAuthTestConfig), so a shared (type, category) pair across two test
        // methods hits AlertsService's "already triggered this month" suppression on whichever method
        // JUnit happens to run second, throwing NoSuchElementException out of seedAlert's orElseThrow().
        Alert alert = seedAlert(session.userId(), AlertType.CATEGORY_OVERSPEND, 8);

        ResponseEntity<Map> response = restTemplate.exchange(
                baseUrl() + "/alerts/" + alert.id() + "/confirm", HttpMethod.POST, new HttpEntity<>(session.headers()), Map.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
    }

    private Alert seedAlert(UUID userId, AlertType type, Integer categoryId) {
        Map<String, Object> payload = categoryId == null ? Map.of() : Map.of("category_id", categoryId);
        return alertsService
                .recordIfNotAlreadyTriggeredThisMonth(userId, type, categoryId, AlertPriority.HIGH, payload)
                .orElseThrow();
    }

    private Alert seedRecurringPaymentAlert(UUID userId, String merchantKey, String merchantLabel, UUID sourceTransactionId) {
        Map<String, Object> payload = Map.of(
                "merchant_key", merchantKey,
                "merchant_label", merchantLabel,
                "representative_amount", BigDecimal.valueOf(199),
                "representative_transaction_id", sourceTransactionId.toString());
        return alertsService
                .recordRecurringPaymentIfNotAlreadyTriggeredThisMonth(userId, merchantKey, BigDecimal.valueOf(199), payload)
                .orElseThrow();
    }

    private UUID insertTransactionDirectly(UUID userId, String upiId, String recipientName, String amount) throws Exception {
        UUID id = UUID.randomUUID();
        try (Connection connection = DriverManager.getConnection(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
                Statement statement = connection.createStatement()) {
            statement.execute("INSERT INTO transactions (id, user_id, transaction_date, debit, credit, amount, "
                    + "transaction_mode, dr_cr_indicator, transaction_id, recipient_name, bank, upi_id, note, source, parsed_at) "
                    + "VALUES ('" + id + "', '" + userId + "', NOW(), " + amount + ", 0, -" + amount + ", 'UPI', 'DR', '" + UUID.randomUUID()
                    + "', '" + recipientName + "', 'ICICI', '" + upiId + "', NULL, 'sms', NOW())");
        }
        return id;
    }

    private int countEmisForSourceTransaction(UUID sourceTransactionId) throws Exception {
        try (Connection connection = DriverManager.getConnection(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
                Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery(
                        "SELECT COUNT(*) AS cnt FROM emis WHERE source_transaction_id = '" + sourceTransactionId + "'")) {
            rs.next();
            return rs.getInt("cnt");
        }
    }

    private Map<?, ?> findAlert(ResponseEntity<Map> list, UUID alertId) {
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> data = (List<Map<String, Object>>) list.getBody().get("data");
        return data.stream().filter(row -> row.get("id").equals(alertId.toString())).findFirst().orElseThrow();
    }

    private Session loginPhone(String phone) {
        ResponseEntity<Map> verify = restTemplate.postForEntity(
                baseUrl() + "/auth/otp/verify",
                Map.of("phone", phone, "idToken", FirebaseAuthTestConfig.VALID_OTP_TOKEN_PHONE_A),
                Map.class);
        return toSession(verify);
    }

    private Session loginGoogle() {
        ResponseEntity<Map> verify = restTemplate.postForEntity(
                baseUrl() + "/auth/google", Map.of("idToken", FirebaseAuthTestConfig.VALID_GOOGLE_TOKEN_A), Map.class);
        return toSession(verify);
    }

    private Session toSession(ResponseEntity<Map> response) {
        String accessToken = (String) response.getBody().get("accessToken");
        String userId = (String) ((Map<?, ?>) response.getBody().get("user")).get("id");
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(accessToken);
        headers.setContentType(MediaType.APPLICATION_JSON);
        return new Session(UUID.fromString(userId), headers);
    }

    private record Session(UUID userId, HttpHeaders headers) {}
}
