package com.spendwise.recommendations;

import com.spendwise.auth.FirebaseAuthTestConfig;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Covers the Required Tests for E8-S2-T2 (docs/api.md `/recommendations`). Requires Docker — run
 * via {@code ./gradlew integrationTest}. Recommendations have no user-facing write endpoint of
 * their own (they're system-generated by {@link RecommendationGeneratorJob}), so this seeds
 * directly through {@link RecommendationsService} — same approach as {@code
 * AlertControllerIntegrationTest}.
 */
@Testcontainers
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(FirebaseAuthTestConfig.class)
class RecommendationControllerIntegrationTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16");

    @Autowired
    private RecommendationsService recommendationsService;

    @Autowired
    private TestRestTemplate restTemplate;

    @LocalServerPort
    private int port;

    private String baseUrl() {
        return "http://localhost:" + port + "/api/v1";
    }

    @Test
    void feedIsOrderedNewestFirst() {
        Session session = loginPhone("+919100000096");
        Recommendation older = seed(session.userId(), 1, "older");
        Recommendation newer = seed(session.userId(), 2, "newer");

        ResponseEntity<List> response =
                restTemplate.exchange(baseUrl() + "/recommendations", HttpMethod.GET, new HttpEntity<>(session.headers()), List.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        List<Map<String, Object>> body = response.getBody();
        assertThat(body).hasSizeGreaterThanOrEqualTo(2);
        int newerIndex = indexOf(body, newer.id());
        int olderIndex = indexOf(body, older.id());
        assertThat(newerIndex).isLessThan(olderIndex);
    }

    @Test
    void dismissThenRefetchExcludesItFromTheFeed() {
        Session session = loginPhone("+919100000097");
        Recommendation seeded = seed(session.userId(), 3, "dismiss me");

        ResponseEntity<Void> dismiss = restTemplate.exchange(
                baseUrl() + "/recommendations/" + seeded.id() + "/dismiss",
                HttpMethod.PUT,
                new HttpEntity<>(session.headers()),
                Void.class);
        assertThat(dismiss.getStatusCode()).isEqualTo(HttpStatus.OK);

        ResponseEntity<List> list =
                restTemplate.exchange(baseUrl() + "/recommendations", HttpMethod.GET, new HttpEntity<>(session.headers()), List.class);
        List<Map<String, Object>> body = list.getBody();
        assertThat(body).extracting(row -> row.get("id")).doesNotContain(seeded.id().toString());
    }

    @Test
    void userBCannotDismissUserAsRecommendation() {
        Session userA = loginPhone("+919100000098");
        Recommendation seeded = seed(userA.userId(), 4, "userA only");
        Session userB = loginGoogle();

        ResponseEntity<Map> response = restTemplate.exchange(
                baseUrl() + "/recommendations/" + seeded.id() + "/dismiss", HttpMethod.PUT, new HttpEntity<>(userB.headers()), Map.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
    }

    private Recommendation seed(UUID userId, int categoryId, String text) {
        return recommendationsService
                .recordIfNoActiveRecommendationExists(userId, categoryId, text, RecommendationPriority.MEDIUM)
                .orElseThrow();
    }

    private int indexOf(List<Map<String, Object>> body, UUID id) {
        for (int i = 0; i < body.size(); i++) {
            if (body.get(i).get("id").equals(id.toString())) {
                return i;
            }
        }
        throw new AssertionError("id not found in response: " + id);
    }

    private Session loginPhone(String phone) {
        ResponseEntity<Map> verify = restTemplate.postForEntity(
                baseUrl() + "/auth/otp/verify",
                Map.of("phone", phone, "idToken", FirebaseAuthTestConfig.VALID_OTP_TOKEN_PHONE_A),
                Map.class);
        return toSession(verify);
    }

    private Session loginGoogle() {
        ResponseEntity<Map> verify = restTemplate.postForEntity(
                baseUrl() + "/auth/google", Map.of("idToken", FirebaseAuthTestConfig.VALID_GOOGLE_TOKEN_A), Map.class);
        return toSession(verify);
    }

    private Session toSession(ResponseEntity<Map> response) {
        String accessToken = (String) response.getBody().get("accessToken");
        String userId = (String) ((Map<?, ?>) response.getBody().get("user")).get("id");
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(accessToken);
        headers.setContentType(MediaType.APPLICATION_JSON);
        return new Session(UUID.fromString(userId), headers);
    }

    private record Session(UUID userId, HttpHeaders headers) {}
}
